FROM alpine:latest
RUN apk add --no-cache bash sudo
RUN apk update && \
# RUN apk add arping
    apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/community lftp
    
RUN apk add --no-cache arp-scan
RUN apk add vim
RUN apk add net-tools
RUN apk add tcpdump

# CMD ["sleep", "infinity", "bash"]
ENTRYPOINT ["tail","-f","/dev/random"]